services:
  godeyes-nginx:
    image: nginx:1.25
    container_name: godeyes-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/streams.d:/etc/nginx/streams.d
      - ./nginx/www:/var/www/certbot
    depends_on:
      - godeyes-registry
    networks:
      - godeyes-network

  godeyes-registry:
    image: registry:2
    container_name: godeyes-registry
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/auth:/auth
    networks:
      - godeyes-network

networks:
  godeyes-network:
    driver: bridge
    external: true
